/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.net.MalformedURLException;

public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        // TestCases tests = new TestCases(); // Initialize your test class

        // TODO: call your test case functions one after other here

        // tests.testCase02();

        // Counthyperlink count = new Counthyperlink();
        // count.testCase01();

        // SearchAmazon searchAma = new SearchAmazon();
        // searchAma.testCase01();

        // LinkedPost post = new LinkedPost();
        // post.testCase01();

        // ImageURL urlimg = new ImageURL();
        // urlimg.testCase01();

        // NestedFrame frame = new NestedFrame();
        // frame.testCase01();

        // WindowHandle handlewindow = new WindowHandle();
        // handlewindow.testCase01();

        IMDBRating IMDB = new IMDBRating();
        IMDB.testCase01();


        // END Tests
        // count.endTest();
        // searchAma.endTest();
        // post.endTest();
        // urlimg.endTest();
        // frame.endTest();
        // handlewindow.endTest();
         IMDB.endTest();

        // tests.endTest(); // End your test by clearning connections and closing
        // browser
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
